import Phaser from 'phaser'

// All assets are real PNG files generated by scripts/generate_assets.py
// To edit sprites: open public/assets/sprites/*.png in LibreSprite
// To regenerate:   python3 scripts/generate_assets.py

export default class BootScene extends Phaser.Scene {
  constructor() {
    super('Boot')
  }

  preload() {
    // Tiles
    this.load.image('tile-floor', 'assets/tiles/floor.png')
    this.load.image('tile-wall',  'assets/tiles/wall.png')
    this.load.image('tile-door',  'assets/tiles/door.png')

    // Character sprites
    this.load.image('player',        'assets/sprites/player.png')
    this.load.image('npc-white',     'assets/sprites/npc-white.png')
    this.load.image('npc-blue',      'assets/sprites/npc-blue.png')
    this.load.image('npc-black',     'assets/sprites/npc-black.png')
    this.load.image('npc-red',       'assets/sprites/npc-red.png')
    this.load.image('npc-green',     'assets/sprites/npc-green.png')
    this.load.image('npc-librarian', 'assets/sprites/npc-librarian.png')
  }

  create() {
    this.scene.start('Title')
  }
}
